name: CI

on: [push]

jobs:
  build-node:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node_version: ['14.20.0','16.17.0','18.7.0']
    steps:
    - uses: actions/checkout@v2
    - run: docker build -t nodejs-old-builder .
    - run: docker run --rm -e NODEJS_VERSION=${{ matrix.node_version }} -v ./node_out:/node_out nodejs-old-builder
    - uses: actions/upload-artifact@v3
      with:
        name: release-tarball
        path: node_out/
