name: CI

on: [push]

jobs:
  build-docker:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        tags: node-js-old-builder:latest
        outputs: type=docker,dest=/tmp/nodejsbuilder.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: nodejsbuilder
        path: /tmp/nodejsbuilder.tar
  build-node:
    runs-on: ubuntu-20.04
    needs: build-docker
    strategy:
        fail-fast: false
        matrix:
          node_version: ['14.20.0','16.17.0','18.7.0']
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: nodejsbuilder
        path: /tmp
    - name: Load Docker image
      run: docker load --input /tmp/nodejsbuilder.tar
    - name: Build Node.js ${{ matrix.node_version }}
      run: docker run --rm -e NODEJS_VERSION=${{ matrix.node_version }} -v /node_out:/node_out node-js-old-builder:latest
    - uses: actions/upload-artifact@v3
      with:
        name: release-tarball
        path: /node_out/
