name: CI

on: [push]

jobs:
  build-node-14:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: docker build -t nodejs-old-builder .
    - run: docker run --rm -e NODEJS_VERSION=14.17.4 -v /node_out:node_out nodejs-old-builder
